#ifndef RESOURCEHEADER_GLOBAL_H
#define RESOURCEHEADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RESOURCEHEADER_LIBRARY)
#  define RESOURCEHEADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RESOURCEHEADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RESOURCEHEADER_GLOBAL_H
