#ifndef USERSMANAGER_GLOBAL_H
#define USERSMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USERSMANAGER_LIBRARY)
#  define USERSMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define USERSMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // USERSMANAGER_GLOBAL_H
