#ifndef DATABASEMANAGER_GLOBAL_H
#define DATABASEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASEMANAGER_LIBRARY)
#  define DATABASEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATABASEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATABASEMANAGER_GLOBAL_H
